### ISSUE TITLE
unknown resource type

### ISSUE THREAD

**Issue by lschierer** [ZloeSabo/puppet-hugo#6]
working with Puppet 2019.8.5 as installed by the AWS Opsworks, and Puppet Development Kit 2.2.0, I'm getting 
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'remote_file' (file: /etc/puppetlabs/code/environments/product│···
ion/modules/hugo/manifests/install.pp, line: 28, column: 9) on node opus95.us-east-1.schierer.name                   
```

my hugo usage is fairly basic,

```puppet

# @summary A short summary of the purpose of this class
#
# A description of what this class does
#
# @example
#   include profile::hugo::schierer_name
class profile::hugo::schierer_name {
  class { 'hugo':
    manage_dependencies => true,
    manage_package      => true,
    package_ensure      => 'present',
    }

}

```

**Comment by lschierer** [comment]
Is this perhaps because I used the version from puppet forge, rather than pulling directly from git?  I see a closed PR about updating the module to work with the PDK from fairly recent.

**Comment by ZloeSabo** [comment]
Hey @lschierer, most likely you did not install `lwf-remote_file` module. AFAIK, puppet does not install module dependencies automagically unless you use something like r10k for your environment, so it's up to you to ensure that all the dependencies are present.
